image:
  repository: localhost/delight-account-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  DB_URL: jdbc:mysql://192.168.68.108:4000/delight-accounts?createDatabaseIfNotExist=true&characterEncoding=UTF-8
  DB_USER: root
  DB_PASSWORD: ""
  LOG_LEVEL: INFO
  LOG_DIR: /var/log/app
  PASSWORD_KEY: sampleSecretKey123
  JWT_SECRET: sampleJwtSecret123sampleJwtSecret123
  JWT_EXPIRATION: "86400000"
